// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODEliteTracker.Database;

#nullable disable

namespace ODEliteTracker.Migrations
{
    [DbContext(typeof(ODEliteTrackerDbContext))]
    [Migration("20250414220159_Settings")]
    partial class Settings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ODJournalDatabase.Database.DTOs.JournalCommanderDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JournalDir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JournalCommanders");
                });

            modelBuilder.Entity("ODJournalDatabase.Database.DTOs.JournalEntryDTO", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnType("TEXT");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommanderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Filename", "Offset");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("TimeStamp", "Offset");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("ODJournalDatabase.Database.DTOs.SettingsDTO", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
